### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by nlemoine** [hacknug/tailwindcss-text-fill-stroke#45]
Hey!

Could you publish a new tag? Requiring the plugin with NPM doesn't match the latest version.

**Comment by alipiry** [comment]
Hey @nlemoine, you can install the beta version using the command below:

`yarn add -D tailwindcss-text-fill-stroke@master`

**Comment by nlemoine** [comment]
Thanks @alipiry, that's what I did but isn't the current version ready for a new tag?

**Comment by alipiry** [comment]
> Thanks @alipiry, that's what I did but isn't the current version ready for a new tag?

You're welcome, I don't know, we should ask the repo author :)

**Comment by nlemoine** [comment]
Oh, sorry, I thought you were the repo author 😄
